# Generated by Django 2.2 on 2020-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201217_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='testproduct'),
            preserve_default=False,
        ),
    ]
